export const TYPE = {
  CREATE_RECIPE: "CREATE_RECIPE",
  READ_ALL_RECIPES: "READ_ALL_RECIPES",
  READ_RECIPE: "READ_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
  DELETE_RECIPE: "DELETE_RECIPE",
  NO_DATA: "NO_DATA",
};
